import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Welcome - Come Take a Look!</title>
                <meta
                    name="Portofilio - Alwin Gilang Permana"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main></main>
        </div>
    )
}

export default Home
